version: "2.3"
services:
  first-node:
    build: .
    container_name: first-node
    volumes:
      - ./base-config:/base-config
      - ./nodes-data/node1:/root/.ethereum
    command: geth --identity="first-node" --networkid="7" --rpcaddr 0.0.0.0

  second-node:
    build: .
    container_name: second-node
    volumes:
      - ./base-config:/base-config
      - ./nodes-data/node2:/root/.ethereum
    command: geth --identity="second-node" --networkid="7" --rpcaddr 0.0.0.0